name: CI

on:
  push:
    branches: [main]      # run on main commits
  pull_request:
    branches: [main]      # and on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.10]   # ✅ valid versions only

    steps:
    # 1. checkout code + LFS files
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0                 # full history helps LFS

    # 2. set up Python + pip cache
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    # 3. install deps
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        pip install -e .

    # 4. lint & format check
    - name: Ruff lint
      run: ruff src scripts tests

    - name: Black format check
      run: black --check src scripts tests

    # 5. run unit tests + nbmake
    - name: Pytest
      run: pytest -q

    # 6. run nbmake on tutorial notebooks (optional; comment out if unnecessary)
    - name: nbmake (notebooks)
      run: |
        pytest --nbmake notebooks/*.ipynb -q
